[tool.black]
line-length = 120

[tool.isort]
profile = "black"
multi_line_output = 3
line_length = 120

[tool.pytest]
testpaths = [
    "tests/integration",
    "tests/unit",
    "tests/discovery",
]
log_cli=true
log_level="info"
